#include <sys/syscall.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
int main(int argc, char** argv){
if (0) ;
else if(strcmp("_sysctl", argv[1]) == 0) printf("%d\n", __NR__sysctl );
else if(strcmp("accept", argv[1]) == 0) printf("%d\n", __NR_accept );
else if(strcmp("accept4", argv[1]) == 0) printf("%d\n", __NR_accept4 );
else if(strcmp("access", argv[1]) == 0) printf("%d\n", __NR_access );
else if(strcmp("acct", argv[1]) == 0) printf("%d\n", __NR_acct );
else if(strcmp("add_key", argv[1]) == 0) printf("%d\n", __NR_add_key );
else if(strcmp("adjtimex", argv[1]) == 0) printf("%d\n", __NR_adjtimex );
else if(strcmp("afs_syscall", argv[1]) == 0) printf("%d\n", __NR_afs_syscall );
else if(strcmp("alarm", argv[1]) == 0) printf("%d\n", __NR_alarm );
else if(strcmp("arch_prctl", argv[1]) == 0) printf("%d\n", __NR_arch_prctl );
else if(strcmp("bind", argv[1]) == 0) printf("%d\n", __NR_bind );
else if(strcmp("bpf", argv[1]) == 0) printf("%d\n", __NR_bpf );
else if(strcmp("brk", argv[1]) == 0) printf("%d\n", __NR_brk );
else if(strcmp("capget", argv[1]) == 0) printf("%d\n", __NR_capget );
else if(strcmp("capset", argv[1]) == 0) printf("%d\n", __NR_capset );
else if(strcmp("chdir", argv[1]) == 0) printf("%d\n", __NR_chdir );
else if(strcmp("chmod", argv[1]) == 0) printf("%d\n", __NR_chmod );
else if(strcmp("chown", argv[1]) == 0) printf("%d\n", __NR_chown );
else if(strcmp("chroot", argv[1]) == 0) printf("%d\n", __NR_chroot );
else if(strcmp("clock_adjtime", argv[1]) == 0) printf("%d\n", __NR_clock_adjtime );
else if(strcmp("clock_getres", argv[1]) == 0) printf("%d\n", __NR_clock_getres );
else if(strcmp("clock_gettime", argv[1]) == 0) printf("%d\n", __NR_clock_gettime );
else if(strcmp("clock_nanosleep", argv[1]) == 0) printf("%d\n", __NR_clock_nanosleep );
else if(strcmp("clock_settime", argv[1]) == 0) printf("%d\n", __NR_clock_settime );
else if(strcmp("clone", argv[1]) == 0) printf("%d\n", __NR_clone );
else if(strcmp("clone3", argv[1]) == 0) printf("%d\n", __NR_clone3 );
else if(strcmp("close", argv[1]) == 0) printf("%d\n", __NR_close );
else if(strcmp("close_range", argv[1]) == 0) printf("%d\n", __NR_close_range );
else if(strcmp("connect", argv[1]) == 0) printf("%d\n", __NR_connect );
else if(strcmp("copy_file_range", argv[1]) == 0) printf("%d\n", __NR_copy_file_range );
else if(strcmp("creat", argv[1]) == 0) printf("%d\n", __NR_creat );
else if(strcmp("create_module", argv[1]) == 0) printf("%d\n", __NR_create_module );
else if(strcmp("delete_module", argv[1]) == 0) printf("%d\n", __NR_delete_module );
else if(strcmp("dup", argv[1]) == 0) printf("%d\n", __NR_dup );
else if(strcmp("dup2", argv[1]) == 0) printf("%d\n", __NR_dup2 );
else if(strcmp("dup3", argv[1]) == 0) printf("%d\n", __NR_dup3 );
else if(strcmp("epoll_create", argv[1]) == 0) printf("%d\n", __NR_epoll_create );
else if(strcmp("epoll_create1", argv[1]) == 0) printf("%d\n", __NR_epoll_create1 );
else if(strcmp("epoll_ctl", argv[1]) == 0) printf("%d\n", __NR_epoll_ctl );
else if(strcmp("epoll_ctl_old", argv[1]) == 0) printf("%d\n", __NR_epoll_ctl_old );
else if(strcmp("epoll_pwait", argv[1]) == 0) printf("%d\n", __NR_epoll_pwait );
else if(strcmp("epoll_wait", argv[1]) == 0) printf("%d\n", __NR_epoll_wait );
else if(strcmp("epoll_wait_old", argv[1]) == 0) printf("%d\n", __NR_epoll_wait_old );
else if(strcmp("eventfd", argv[1]) == 0) printf("%d\n", __NR_eventfd );
else if(strcmp("eventfd2", argv[1]) == 0) printf("%d\n", __NR_eventfd2 );
else if(strcmp("execve", argv[1]) == 0) printf("%d\n", __NR_execve );
else if(strcmp("execveat", argv[1]) == 0) printf("%d\n", __NR_execveat );
else if(strcmp("exit", argv[1]) == 0) printf("%d\n", __NR_exit );
else if(strcmp("exit_group", argv[1]) == 0) printf("%d\n", __NR_exit_group );
else if(strcmp("faccessat", argv[1]) == 0) printf("%d\n", __NR_faccessat );
else if(strcmp("faccessat2", argv[1]) == 0) printf("%d\n", __NR_faccessat2 );
else if(strcmp("fadvise64", argv[1]) == 0) printf("%d\n", __NR_fadvise64 );
else if(strcmp("fallocate", argv[1]) == 0) printf("%d\n", __NR_fallocate );
else if(strcmp("fanotify_init", argv[1]) == 0) printf("%d\n", __NR_fanotify_init );
else if(strcmp("fanotify_mark", argv[1]) == 0) printf("%d\n", __NR_fanotify_mark );
else if(strcmp("fchdir", argv[1]) == 0) printf("%d\n", __NR_fchdir );
else if(strcmp("fchmod", argv[1]) == 0) printf("%d\n", __NR_fchmod );
else if(strcmp("fchmodat", argv[1]) == 0) printf("%d\n", __NR_fchmodat );
else if(strcmp("fchown", argv[1]) == 0) printf("%d\n", __NR_fchown );
else if(strcmp("fchownat", argv[1]) == 0) printf("%d\n", __NR_fchownat );
else if(strcmp("fcntl", argv[1]) == 0) printf("%d\n", __NR_fcntl );
else if(strcmp("fdatasync", argv[1]) == 0) printf("%d\n", __NR_fdatasync );
else if(strcmp("fgetxattr", argv[1]) == 0) printf("%d\n", __NR_fgetxattr );
else if(strcmp("finit_module", argv[1]) == 0) printf("%d\n", __NR_finit_module );
else if(strcmp("flistxattr", argv[1]) == 0) printf("%d\n", __NR_flistxattr );
else if(strcmp("flock", argv[1]) == 0) printf("%d\n", __NR_flock );
else if(strcmp("fork", argv[1]) == 0) printf("%d\n", __NR_fork );
else if(strcmp("fremovexattr", argv[1]) == 0) printf("%d\n", __NR_fremovexattr );
else if(strcmp("fsconfig", argv[1]) == 0) printf("%d\n", __NR_fsconfig );
else if(strcmp("fsetxattr", argv[1]) == 0) printf("%d\n", __NR_fsetxattr );
else if(strcmp("fsmount", argv[1]) == 0) printf("%d\n", __NR_fsmount );
else if(strcmp("fsopen", argv[1]) == 0) printf("%d\n", __NR_fsopen );
else if(strcmp("fspick", argv[1]) == 0) printf("%d\n", __NR_fspick );
else if(strcmp("fstat", argv[1]) == 0) printf("%d\n", __NR_fstat );
else if(strcmp("fstatfs", argv[1]) == 0) printf("%d\n", __NR_fstatfs );
else if(strcmp("fsync", argv[1]) == 0) printf("%d\n", __NR_fsync );
else if(strcmp("ftruncate", argv[1]) == 0) printf("%d\n", __NR_ftruncate );
else if(strcmp("futex", argv[1]) == 0) printf("%d\n", __NR_futex );
else if(strcmp("futimesat", argv[1]) == 0) printf("%d\n", __NR_futimesat );
else if(strcmp("get_kernel_syms", argv[1]) == 0) printf("%d\n", __NR_get_kernel_syms );
else if(strcmp("get_mempolicy", argv[1]) == 0) printf("%d\n", __NR_get_mempolicy );
else if(strcmp("get_robust_list", argv[1]) == 0) printf("%d\n", __NR_get_robust_list );
else if(strcmp("get_thread_area", argv[1]) == 0) printf("%d\n", __NR_get_thread_area );
else if(strcmp("getcpu", argv[1]) == 0) printf("%d\n", __NR_getcpu );
else if(strcmp("getcwd", argv[1]) == 0) printf("%d\n", __NR_getcwd );
else if(strcmp("getdents", argv[1]) == 0) printf("%d\n", __NR_getdents );
else if(strcmp("getdents64", argv[1]) == 0) printf("%d\n", __NR_getdents64 );
else if(strcmp("getegid", argv[1]) == 0) printf("%d\n", __NR_getegid );
else if(strcmp("geteuid", argv[1]) == 0) printf("%d\n", __NR_geteuid );
else if(strcmp("getgid", argv[1]) == 0) printf("%d\n", __NR_getgid );
else if(strcmp("getgroups", argv[1]) == 0) printf("%d\n", __NR_getgroups );
else if(strcmp("getitimer", argv[1]) == 0) printf("%d\n", __NR_getitimer );
else if(strcmp("getpeername", argv[1]) == 0) printf("%d\n", __NR_getpeername );
else if(strcmp("getpgid", argv[1]) == 0) printf("%d\n", __NR_getpgid );
else if(strcmp("getpgrp", argv[1]) == 0) printf("%d\n", __NR_getpgrp );
else if(strcmp("getpid", argv[1]) == 0) printf("%d\n", __NR_getpid );
else if(strcmp("getpmsg", argv[1]) == 0) printf("%d\n", __NR_getpmsg );
else if(strcmp("getppid", argv[1]) == 0) printf("%d\n", __NR_getppid );
else if(strcmp("getpriority", argv[1]) == 0) printf("%d\n", __NR_getpriority );
else if(strcmp("getrandom", argv[1]) == 0) printf("%d\n", __NR_getrandom );
else if(strcmp("getresgid", argv[1]) == 0) printf("%d\n", __NR_getresgid );
else if(strcmp("getresuid", argv[1]) == 0) printf("%d\n", __NR_getresuid );
else if(strcmp("getrlimit", argv[1]) == 0) printf("%d\n", __NR_getrlimit );
else if(strcmp("getrusage", argv[1]) == 0) printf("%d\n", __NR_getrusage );
else if(strcmp("getsid", argv[1]) == 0) printf("%d\n", __NR_getsid );
else if(strcmp("getsockname", argv[1]) == 0) printf("%d\n", __NR_getsockname );
else if(strcmp("getsockopt", argv[1]) == 0) printf("%d\n", __NR_getsockopt );
else if(strcmp("gettid", argv[1]) == 0) printf("%d\n", __NR_gettid );
else if(strcmp("gettimeofday", argv[1]) == 0) printf("%d\n", __NR_gettimeofday );
else if(strcmp("getuid", argv[1]) == 0) printf("%d\n", __NR_getuid );
else if(strcmp("getxattr", argv[1]) == 0) printf("%d\n", __NR_getxattr );
else if(strcmp("init_module", argv[1]) == 0) printf("%d\n", __NR_init_module );
else if(strcmp("inotify_add_watch", argv[1]) == 0) printf("%d\n", __NR_inotify_add_watch );
else if(strcmp("inotify_init", argv[1]) == 0) printf("%d\n", __NR_inotify_init );
else if(strcmp("inotify_init1", argv[1]) == 0) printf("%d\n", __NR_inotify_init1 );
else if(strcmp("inotify_rm_watch", argv[1]) == 0) printf("%d\n", __NR_inotify_rm_watch );
else if(strcmp("io_cancel", argv[1]) == 0) printf("%d\n", __NR_io_cancel );
else if(strcmp("io_destroy", argv[1]) == 0) printf("%d\n", __NR_io_destroy );
else if(strcmp("io_getevents", argv[1]) == 0) printf("%d\n", __NR_io_getevents );
else if(strcmp("io_pgetevents", argv[1]) == 0) printf("%d\n", __NR_io_pgetevents );
else if(strcmp("io_setup", argv[1]) == 0) printf("%d\n", __NR_io_setup );
else if(strcmp("io_submit", argv[1]) == 0) printf("%d\n", __NR_io_submit );
else if(strcmp("io_uring_enter", argv[1]) == 0) printf("%d\n", __NR_io_uring_enter );
else if(strcmp("io_uring_register", argv[1]) == 0) printf("%d\n", __NR_io_uring_register );
else if(strcmp("io_uring_setup", argv[1]) == 0) printf("%d\n", __NR_io_uring_setup );
else if(strcmp("ioctl", argv[1]) == 0) printf("%d\n", __NR_ioctl );
else if(strcmp("ioperm", argv[1]) == 0) printf("%d\n", __NR_ioperm );
else if(strcmp("iopl", argv[1]) == 0) printf("%d\n", __NR_iopl );
else if(strcmp("ioprio_get", argv[1]) == 0) printf("%d\n", __NR_ioprio_get );
else if(strcmp("ioprio_set", argv[1]) == 0) printf("%d\n", __NR_ioprio_set );
else if(strcmp("kcmp", argv[1]) == 0) printf("%d\n", __NR_kcmp );
else if(strcmp("kexec_file_load", argv[1]) == 0) printf("%d\n", __NR_kexec_file_load );
else if(strcmp("kexec_load", argv[1]) == 0) printf("%d\n", __NR_kexec_load );
else if(strcmp("keyctl", argv[1]) == 0) printf("%d\n", __NR_keyctl );
else if(strcmp("kill", argv[1]) == 0) printf("%d\n", __NR_kill );
else if(strcmp("lchown", argv[1]) == 0) printf("%d\n", __NR_lchown );
else if(strcmp("lgetxattr", argv[1]) == 0) printf("%d\n", __NR_lgetxattr );
else if(strcmp("link", argv[1]) == 0) printf("%d\n", __NR_link );
else if(strcmp("linkat", argv[1]) == 0) printf("%d\n", __NR_linkat );
else if(strcmp("listen", argv[1]) == 0) printf("%d\n", __NR_listen );
else if(strcmp("listxattr", argv[1]) == 0) printf("%d\n", __NR_listxattr );
else if(strcmp("llistxattr", argv[1]) == 0) printf("%d\n", __NR_llistxattr );
else if(strcmp("lookup_dcookie", argv[1]) == 0) printf("%d\n", __NR_lookup_dcookie );
else if(strcmp("lremovexattr", argv[1]) == 0) printf("%d\n", __NR_lremovexattr );
else if(strcmp("lseek", argv[1]) == 0) printf("%d\n", __NR_lseek );
else if(strcmp("lsetxattr", argv[1]) == 0) printf("%d\n", __NR_lsetxattr );
else if(strcmp("lstat", argv[1]) == 0) printf("%d\n", __NR_lstat );
else if(strcmp("madvise", argv[1]) == 0) printf("%d\n", __NR_madvise );
else if(strcmp("mbind", argv[1]) == 0) printf("%d\n", __NR_mbind );
else if(strcmp("membarrier", argv[1]) == 0) printf("%d\n", __NR_membarrier );
else if(strcmp("memfd_create", argv[1]) == 0) printf("%d\n", __NR_memfd_create );
else if(strcmp("migrate_pages", argv[1]) == 0) printf("%d\n", __NR_migrate_pages );
else if(strcmp("mincore", argv[1]) == 0) printf("%d\n", __NR_mincore );
else if(strcmp("mkdir", argv[1]) == 0) printf("%d\n", __NR_mkdir );
else if(strcmp("mkdirat", argv[1]) == 0) printf("%d\n", __NR_mkdirat );
else if(strcmp("mknod", argv[1]) == 0) printf("%d\n", __NR_mknod );
else if(strcmp("mknodat", argv[1]) == 0) printf("%d\n", __NR_mknodat );
else if(strcmp("mlock", argv[1]) == 0) printf("%d\n", __NR_mlock );
else if(strcmp("mlock2", argv[1]) == 0) printf("%d\n", __NR_mlock2 );
else if(strcmp("mlockall", argv[1]) == 0) printf("%d\n", __NR_mlockall );
else if(strcmp("mmap", argv[1]) == 0) printf("%d\n", __NR_mmap );
else if(strcmp("modify_ldt", argv[1]) == 0) printf("%d\n", __NR_modify_ldt );
else if(strcmp("mount", argv[1]) == 0) printf("%d\n", __NR_mount );
else if(strcmp("move_mount", argv[1]) == 0) printf("%d\n", __NR_move_mount );
else if(strcmp("move_pages", argv[1]) == 0) printf("%d\n", __NR_move_pages );
else if(strcmp("mprotect", argv[1]) == 0) printf("%d\n", __NR_mprotect );
else if(strcmp("mq_getsetattr", argv[1]) == 0) printf("%d\n", __NR_mq_getsetattr );
else if(strcmp("mq_notify", argv[1]) == 0) printf("%d\n", __NR_mq_notify );
else if(strcmp("mq_open", argv[1]) == 0) printf("%d\n", __NR_mq_open );
else if(strcmp("mq_timedreceive", argv[1]) == 0) printf("%d\n", __NR_mq_timedreceive );
else if(strcmp("mq_timedsend", argv[1]) == 0) printf("%d\n", __NR_mq_timedsend );
else if(strcmp("mq_unlink", argv[1]) == 0) printf("%d\n", __NR_mq_unlink );
else if(strcmp("mremap", argv[1]) == 0) printf("%d\n", __NR_mremap );
else if(strcmp("msgctl", argv[1]) == 0) printf("%d\n", __NR_msgctl );
else if(strcmp("msgget", argv[1]) == 0) printf("%d\n", __NR_msgget );
else if(strcmp("msgrcv", argv[1]) == 0) printf("%d\n", __NR_msgrcv );
else if(strcmp("msgsnd", argv[1]) == 0) printf("%d\n", __NR_msgsnd );
else if(strcmp("msync", argv[1]) == 0) printf("%d\n", __NR_msync );
else if(strcmp("munlock", argv[1]) == 0) printf("%d\n", __NR_munlock );
else if(strcmp("munlockall", argv[1]) == 0) printf("%d\n", __NR_munlockall );
else if(strcmp("munmap", argv[1]) == 0) printf("%d\n", __NR_munmap );
else if(strcmp("name_to_handle_at", argv[1]) == 0) printf("%d\n", __NR_name_to_handle_at );
else if(strcmp("nanosleep", argv[1]) == 0) printf("%d\n", __NR_nanosleep );
else if(strcmp("newfstatat", argv[1]) == 0) printf("%d\n", __NR_newfstatat );
else if(strcmp("nfsservctl", argv[1]) == 0) printf("%d\n", __NR_nfsservctl );
else if(strcmp("open", argv[1]) == 0) printf("%d\n", __NR_open );
else if(strcmp("open_by_handle_at", argv[1]) == 0) printf("%d\n", __NR_open_by_handle_at );
else if(strcmp("open_tree", argv[1]) == 0) printf("%d\n", __NR_open_tree );
else if(strcmp("openat", argv[1]) == 0) printf("%d\n", __NR_openat );
else if(strcmp("openat2", argv[1]) == 0) printf("%d\n", __NR_openat2 );
else if(strcmp("pause", argv[1]) == 0) printf("%d\n", __NR_pause );
else if(strcmp("perf_event_open", argv[1]) == 0) printf("%d\n", __NR_perf_event_open );
else if(strcmp("personality", argv[1]) == 0) printf("%d\n", __NR_personality );
else if(strcmp("pidfd_getfd", argv[1]) == 0) printf("%d\n", __NR_pidfd_getfd );
else if(strcmp("pidfd_open", argv[1]) == 0) printf("%d\n", __NR_pidfd_open );
else if(strcmp("pidfd_send_signal", argv[1]) == 0) printf("%d\n", __NR_pidfd_send_signal );
else if(strcmp("pipe", argv[1]) == 0) printf("%d\n", __NR_pipe );
else if(strcmp("pipe2", argv[1]) == 0) printf("%d\n", __NR_pipe2 );
else if(strcmp("pivot_root", argv[1]) == 0) printf("%d\n", __NR_pivot_root );
else if(strcmp("pkey_alloc", argv[1]) == 0) printf("%d\n", __NR_pkey_alloc );
else if(strcmp("pkey_free", argv[1]) == 0) printf("%d\n", __NR_pkey_free );
else if(strcmp("pkey_mprotect", argv[1]) == 0) printf("%d\n", __NR_pkey_mprotect );
else if(strcmp("poll", argv[1]) == 0) printf("%d\n", __NR_poll );
else if(strcmp("ppoll", argv[1]) == 0) printf("%d\n", __NR_ppoll );
else if(strcmp("prctl", argv[1]) == 0) printf("%d\n", __NR_prctl );
else if(strcmp("pread64", argv[1]) == 0) printf("%d\n", __NR_pread64 );
else if(strcmp("preadv", argv[1]) == 0) printf("%d\n", __NR_preadv );
else if(strcmp("preadv2", argv[1]) == 0) printf("%d\n", __NR_preadv2 );
else if(strcmp("prlimit64", argv[1]) == 0) printf("%d\n", __NR_prlimit64 );
else if(strcmp("process_madvise", argv[1]) == 0) printf("%d\n", __NR_process_madvise );
else if(strcmp("process_vm_readv", argv[1]) == 0) printf("%d\n", __NR_process_vm_readv );
else if(strcmp("process_vm_writev", argv[1]) == 0) printf("%d\n", __NR_process_vm_writev );
else if(strcmp("pselect6", argv[1]) == 0) printf("%d\n", __NR_pselect6 );
else if(strcmp("ptrace", argv[1]) == 0) printf("%d\n", __NR_ptrace );
else if(strcmp("putpmsg", argv[1]) == 0) printf("%d\n", __NR_putpmsg );
else if(strcmp("pwrite64", argv[1]) == 0) printf("%d\n", __NR_pwrite64 );
else if(strcmp("pwritev", argv[1]) == 0) printf("%d\n", __NR_pwritev );
else if(strcmp("pwritev2", argv[1]) == 0) printf("%d\n", __NR_pwritev2 );
else if(strcmp("query_module", argv[1]) == 0) printf("%d\n", __NR_query_module );
else if(strcmp("quotactl", argv[1]) == 0) printf("%d\n", __NR_quotactl );
else if(strcmp("read", argv[1]) == 0) printf("%d\n", __NR_read );
else if(strcmp("readahead", argv[1]) == 0) printf("%d\n", __NR_readahead );
else if(strcmp("readlink", argv[1]) == 0) printf("%d\n", __NR_readlink );
else if(strcmp("readlinkat", argv[1]) == 0) printf("%d\n", __NR_readlinkat );
else if(strcmp("readv", argv[1]) == 0) printf("%d\n", __NR_readv );
else if(strcmp("reboot", argv[1]) == 0) printf("%d\n", __NR_reboot );
else if(strcmp("recvfrom", argv[1]) == 0) printf("%d\n", __NR_recvfrom );
else if(strcmp("recvmmsg", argv[1]) == 0) printf("%d\n", __NR_recvmmsg );
else if(strcmp("recvmsg", argv[1]) == 0) printf("%d\n", __NR_recvmsg );
else if(strcmp("remap_file_pages", argv[1]) == 0) printf("%d\n", __NR_remap_file_pages );
else if(strcmp("removexattr", argv[1]) == 0) printf("%d\n", __NR_removexattr );
else if(strcmp("rename", argv[1]) == 0) printf("%d\n", __NR_rename );
else if(strcmp("renameat", argv[1]) == 0) printf("%d\n", __NR_renameat );
else if(strcmp("renameat2", argv[1]) == 0) printf("%d\n", __NR_renameat2 );
else if(strcmp("request_key", argv[1]) == 0) printf("%d\n", __NR_request_key );
else if(strcmp("restart_syscall", argv[1]) == 0) printf("%d\n", __NR_restart_syscall );
else if(strcmp("rmdir", argv[1]) == 0) printf("%d\n", __NR_rmdir );
else if(strcmp("rseq", argv[1]) == 0) printf("%d\n", __NR_rseq );
else if(strcmp("rt_sigaction", argv[1]) == 0) printf("%d\n", __NR_rt_sigaction );
else if(strcmp("rt_sigpending", argv[1]) == 0) printf("%d\n", __NR_rt_sigpending );
else if(strcmp("rt_sigprocmask", argv[1]) == 0) printf("%d\n", __NR_rt_sigprocmask );
else if(strcmp("rt_sigqueueinfo", argv[1]) == 0) printf("%d\n", __NR_rt_sigqueueinfo );
else if(strcmp("rt_sigreturn", argv[1]) == 0) printf("%d\n", __NR_rt_sigreturn );
else if(strcmp("rt_sigsuspend", argv[1]) == 0) printf("%d\n", __NR_rt_sigsuspend );
else if(strcmp("rt_sigtimedwait", argv[1]) == 0) printf("%d\n", __NR_rt_sigtimedwait );
else if(strcmp("rt_tgsigqueueinfo", argv[1]) == 0) printf("%d\n", __NR_rt_tgsigqueueinfo );
else if(strcmp("sched_get_priority_max", argv[1]) == 0) printf("%d\n", __NR_sched_get_priority_max );
else if(strcmp("sched_get_priority_min", argv[1]) == 0) printf("%d\n", __NR_sched_get_priority_min );
else if(strcmp("sched_getaffinity", argv[1]) == 0) printf("%d\n", __NR_sched_getaffinity );
else if(strcmp("sched_getattr", argv[1]) == 0) printf("%d\n", __NR_sched_getattr );
else if(strcmp("sched_getparam", argv[1]) == 0) printf("%d\n", __NR_sched_getparam );
else if(strcmp("sched_getscheduler", argv[1]) == 0) printf("%d\n", __NR_sched_getscheduler );
else if(strcmp("sched_rr_get_interval", argv[1]) == 0) printf("%d\n", __NR_sched_rr_get_interval );
else if(strcmp("sched_setaffinity", argv[1]) == 0) printf("%d\n", __NR_sched_setaffinity );
else if(strcmp("sched_setattr", argv[1]) == 0) printf("%d\n", __NR_sched_setattr );
else if(strcmp("sched_setparam", argv[1]) == 0) printf("%d\n", __NR_sched_setparam );
else if(strcmp("sched_setscheduler", argv[1]) == 0) printf("%d\n", __NR_sched_setscheduler );
else if(strcmp("sched_yield", argv[1]) == 0) printf("%d\n", __NR_sched_yield );
else if(strcmp("seccomp", argv[1]) == 0) printf("%d\n", __NR_seccomp );
else if(strcmp("security", argv[1]) == 0) printf("%d\n", __NR_security );
else if(strcmp("select", argv[1]) == 0) printf("%d\n", __NR_select );
else if(strcmp("semctl", argv[1]) == 0) printf("%d\n", __NR_semctl );
else if(strcmp("semget", argv[1]) == 0) printf("%d\n", __NR_semget );
else if(strcmp("semop", argv[1]) == 0) printf("%d\n", __NR_semop );
else if(strcmp("semtimedop", argv[1]) == 0) printf("%d\n", __NR_semtimedop );
else if(strcmp("sendfile", argv[1]) == 0) printf("%d\n", __NR_sendfile );
else if(strcmp("sendmmsg", argv[1]) == 0) printf("%d\n", __NR_sendmmsg );
else if(strcmp("sendmsg", argv[1]) == 0) printf("%d\n", __NR_sendmsg );
else if(strcmp("sendto", argv[1]) == 0) printf("%d\n", __NR_sendto );
else if(strcmp("set_mempolicy", argv[1]) == 0) printf("%d\n", __NR_set_mempolicy );
else if(strcmp("set_robust_list", argv[1]) == 0) printf("%d\n", __NR_set_robust_list );
else if(strcmp("set_thread_area", argv[1]) == 0) printf("%d\n", __NR_set_thread_area );
else if(strcmp("set_tid_address", argv[1]) == 0) printf("%d\n", __NR_set_tid_address );
else if(strcmp("setdomainname", argv[1]) == 0) printf("%d\n", __NR_setdomainname );
else if(strcmp("setfsgid", argv[1]) == 0) printf("%d\n", __NR_setfsgid );
else if(strcmp("setfsuid", argv[1]) == 0) printf("%d\n", __NR_setfsuid );
else if(strcmp("setgid", argv[1]) == 0) printf("%d\n", __NR_setgid );
else if(strcmp("setgroups", argv[1]) == 0) printf("%d\n", __NR_setgroups );
else if(strcmp("sethostname", argv[1]) == 0) printf("%d\n", __NR_sethostname );
else if(strcmp("setitimer", argv[1]) == 0) printf("%d\n", __NR_setitimer );
else if(strcmp("setns", argv[1]) == 0) printf("%d\n", __NR_setns );
else if(strcmp("setpgid", argv[1]) == 0) printf("%d\n", __NR_setpgid );
else if(strcmp("setpriority", argv[1]) == 0) printf("%d\n", __NR_setpriority );
else if(strcmp("setregid", argv[1]) == 0) printf("%d\n", __NR_setregid );
else if(strcmp("setresgid", argv[1]) == 0) printf("%d\n", __NR_setresgid );
else if(strcmp("setresuid", argv[1]) == 0) printf("%d\n", __NR_setresuid );
else if(strcmp("setreuid", argv[1]) == 0) printf("%d\n", __NR_setreuid );
else if(strcmp("setrlimit", argv[1]) == 0) printf("%d\n", __NR_setrlimit );
else if(strcmp("setsid", argv[1]) == 0) printf("%d\n", __NR_setsid );
else if(strcmp("setsockopt", argv[1]) == 0) printf("%d\n", __NR_setsockopt );
else if(strcmp("settimeofday", argv[1]) == 0) printf("%d\n", __NR_settimeofday );
else if(strcmp("setuid", argv[1]) == 0) printf("%d\n", __NR_setuid );
else if(strcmp("setxattr", argv[1]) == 0) printf("%d\n", __NR_setxattr );
else if(strcmp("shmat", argv[1]) == 0) printf("%d\n", __NR_shmat );
else if(strcmp("shmctl", argv[1]) == 0) printf("%d\n", __NR_shmctl );
else if(strcmp("shmdt", argv[1]) == 0) printf("%d\n", __NR_shmdt );
else if(strcmp("shmget", argv[1]) == 0) printf("%d\n", __NR_shmget );
else if(strcmp("shutdown", argv[1]) == 0) printf("%d\n", __NR_shutdown );
else if(strcmp("sigaltstack", argv[1]) == 0) printf("%d\n", __NR_sigaltstack );
else if(strcmp("signalfd", argv[1]) == 0) printf("%d\n", __NR_signalfd );
else if(strcmp("signalfd4", argv[1]) == 0) printf("%d\n", __NR_signalfd4 );
else if(strcmp("socket", argv[1]) == 0) printf("%d\n", __NR_socket );
else if(strcmp("socketpair", argv[1]) == 0) printf("%d\n", __NR_socketpair );
else if(strcmp("splice", argv[1]) == 0) printf("%d\n", __NR_splice );
else if(strcmp("stat", argv[1]) == 0) printf("%d\n", __NR_stat );
else if(strcmp("statfs", argv[1]) == 0) printf("%d\n", __NR_statfs );
else if(strcmp("statx", argv[1]) == 0) printf("%d\n", __NR_statx );
else if(strcmp("swapoff", argv[1]) == 0) printf("%d\n", __NR_swapoff );
else if(strcmp("swapon", argv[1]) == 0) printf("%d\n", __NR_swapon );
else if(strcmp("symlink", argv[1]) == 0) printf("%d\n", __NR_symlink );
else if(strcmp("symlinkat", argv[1]) == 0) printf("%d\n", __NR_symlinkat );
else if(strcmp("sync", argv[1]) == 0) printf("%d\n", __NR_sync );
else if(strcmp("sync_file_range", argv[1]) == 0) printf("%d\n", __NR_sync_file_range );
else if(strcmp("syncfs", argv[1]) == 0) printf("%d\n", __NR_syncfs );
else if(strcmp("sysfs", argv[1]) == 0) printf("%d\n", __NR_sysfs );
else if(strcmp("sysinfo", argv[1]) == 0) printf("%d\n", __NR_sysinfo );
else if(strcmp("syslog", argv[1]) == 0) printf("%d\n", __NR_syslog );
else if(strcmp("tee", argv[1]) == 0) printf("%d\n", __NR_tee );
else if(strcmp("tgkill", argv[1]) == 0) printf("%d\n", __NR_tgkill );
else if(strcmp("time", argv[1]) == 0) printf("%d\n", __NR_time );
else if(strcmp("timer_create", argv[1]) == 0) printf("%d\n", __NR_timer_create );
else if(strcmp("timer_delete", argv[1]) == 0) printf("%d\n", __NR_timer_delete );
else if(strcmp("timer_getoverrun", argv[1]) == 0) printf("%d\n", __NR_timer_getoverrun );
else if(strcmp("timer_gettime", argv[1]) == 0) printf("%d\n", __NR_timer_gettime );
else if(strcmp("timer_settime", argv[1]) == 0) printf("%d\n", __NR_timer_settime );
else if(strcmp("timerfd_create", argv[1]) == 0) printf("%d\n", __NR_timerfd_create );
else if(strcmp("timerfd_gettime", argv[1]) == 0) printf("%d\n", __NR_timerfd_gettime );
else if(strcmp("timerfd_settime", argv[1]) == 0) printf("%d\n", __NR_timerfd_settime );
else if(strcmp("times", argv[1]) == 0) printf("%d\n", __NR_times );
else if(strcmp("tkill", argv[1]) == 0) printf("%d\n", __NR_tkill );
else if(strcmp("truncate", argv[1]) == 0) printf("%d\n", __NR_truncate );
else if(strcmp("tuxcall", argv[1]) == 0) printf("%d\n", __NR_tuxcall );
else if(strcmp("umask", argv[1]) == 0) printf("%d\n", __NR_umask );
else if(strcmp("umount2", argv[1]) == 0) printf("%d\n", __NR_umount2 );
else if(strcmp("uname", argv[1]) == 0) printf("%d\n", __NR_uname );
else if(strcmp("unlink", argv[1]) == 0) printf("%d\n", __NR_unlink );
else if(strcmp("unlinkat", argv[1]) == 0) printf("%d\n", __NR_unlinkat );
else if(strcmp("unshare", argv[1]) == 0) printf("%d\n", __NR_unshare );
else if(strcmp("uselib", argv[1]) == 0) printf("%d\n", __NR_uselib );
else if(strcmp("userfaultfd", argv[1]) == 0) printf("%d\n", __NR_userfaultfd );
else if(strcmp("ustat", argv[1]) == 0) printf("%d\n", __NR_ustat );
else if(strcmp("utime", argv[1]) == 0) printf("%d\n", __NR_utime );
else if(strcmp("utimensat", argv[1]) == 0) printf("%d\n", __NR_utimensat );
else if(strcmp("utimes", argv[1]) == 0) printf("%d\n", __NR_utimes );
else if(strcmp("vfork", argv[1]) == 0) printf("%d\n", __NR_vfork );
else if(strcmp("vhangup", argv[1]) == 0) printf("%d\n", __NR_vhangup );
else if(strcmp("vmsplice", argv[1]) == 0) printf("%d\n", __NR_vmsplice );
else if(strcmp("vserver", argv[1]) == 0) printf("%d\n", __NR_vserver );
else if(strcmp("wait4", argv[1]) == 0) printf("%d\n", __NR_wait4 );
else if(strcmp("waitid", argv[1]) == 0) printf("%d\n", __NR_waitid );
else if(strcmp("write", argv[1]) == 0) printf("%d\n", __NR_write );
else if(strcmp("writev", argv[1]) == 0) printf("%d\n", __NR_writev );
else if(__NR__sysctl == atoi(argv[1])) printf("%s\n", "_sysctl" );
else if(__NR_accept == atoi(argv[1])) printf("%s\n", "accept" );
else if(__NR_accept4 == atoi(argv[1])) printf("%s\n", "accept4" );
else if(__NR_access == atoi(argv[1])) printf("%s\n", "access" );
else if(__NR_acct == atoi(argv[1])) printf("%s\n", "acct" );
else if(__NR_add_key == atoi(argv[1])) printf("%s\n", "add_key" );
else if(__NR_adjtimex == atoi(argv[1])) printf("%s\n", "adjtimex" );
else if(__NR_afs_syscall == atoi(argv[1])) printf("%s\n", "afs_syscall" );
else if(__NR_alarm == atoi(argv[1])) printf("%s\n", "alarm" );
else if(__NR_arch_prctl == atoi(argv[1])) printf("%s\n", "arch_prctl" );
else if(__NR_bind == atoi(argv[1])) printf("%s\n", "bind" );
else if(__NR_bpf == atoi(argv[1])) printf("%s\n", "bpf" );
else if(__NR_brk == atoi(argv[1])) printf("%s\n", "brk" );
else if(__NR_capget == atoi(argv[1])) printf("%s\n", "capget" );
else if(__NR_capset == atoi(argv[1])) printf("%s\n", "capset" );
else if(__NR_chdir == atoi(argv[1])) printf("%s\n", "chdir" );
else if(__NR_chmod == atoi(argv[1])) printf("%s\n", "chmod" );
else if(__NR_chown == atoi(argv[1])) printf("%s\n", "chown" );
else if(__NR_chroot == atoi(argv[1])) printf("%s\n", "chroot" );
else if(__NR_clock_adjtime == atoi(argv[1])) printf("%s\n", "clock_adjtime" );
else if(__NR_clock_getres == atoi(argv[1])) printf("%s\n", "clock_getres" );
else if(__NR_clock_gettime == atoi(argv[1])) printf("%s\n", "clock_gettime" );
else if(__NR_clock_nanosleep == atoi(argv[1])) printf("%s\n", "clock_nanosleep" );
else if(__NR_clock_settime == atoi(argv[1])) printf("%s\n", "clock_settime" );
else if(__NR_clone == atoi(argv[1])) printf("%s\n", "clone" );
else if(__NR_clone3 == atoi(argv[1])) printf("%s\n", "clone3" );
else if(__NR_close == atoi(argv[1])) printf("%s\n", "close" );
else if(__NR_close_range == atoi(argv[1])) printf("%s\n", "close_range" );
else if(__NR_connect == atoi(argv[1])) printf("%s\n", "connect" );
else if(__NR_copy_file_range == atoi(argv[1])) printf("%s\n", "copy_file_range" );
else if(__NR_creat == atoi(argv[1])) printf("%s\n", "creat" );
else if(__NR_create_module == atoi(argv[1])) printf("%s\n", "create_module" );
else if(__NR_delete_module == atoi(argv[1])) printf("%s\n", "delete_module" );
else if(__NR_dup == atoi(argv[1])) printf("%s\n", "dup" );
else if(__NR_dup2 == atoi(argv[1])) printf("%s\n", "dup2" );
else if(__NR_dup3 == atoi(argv[1])) printf("%s\n", "dup3" );
else if(__NR_epoll_create == atoi(argv[1])) printf("%s\n", "epoll_create" );
else if(__NR_epoll_create1 == atoi(argv[1])) printf("%s\n", "epoll_create1" );
else if(__NR_epoll_ctl == atoi(argv[1])) printf("%s\n", "epoll_ctl" );
else if(__NR_epoll_ctl_old == atoi(argv[1])) printf("%s\n", "epoll_ctl_old" );
else if(__NR_epoll_pwait == atoi(argv[1])) printf("%s\n", "epoll_pwait" );
else if(__NR_epoll_wait == atoi(argv[1])) printf("%s\n", "epoll_wait" );
else if(__NR_epoll_wait_old == atoi(argv[1])) printf("%s\n", "epoll_wait_old" );
else if(__NR_eventfd == atoi(argv[1])) printf("%s\n", "eventfd" );
else if(__NR_eventfd2 == atoi(argv[1])) printf("%s\n", "eventfd2" );
else if(__NR_execve == atoi(argv[1])) printf("%s\n", "execve" );
else if(__NR_execveat == atoi(argv[1])) printf("%s\n", "execveat" );
else if(__NR_exit == atoi(argv[1])) printf("%s\n", "exit" );
else if(__NR_exit_group == atoi(argv[1])) printf("%s\n", "exit_group" );
else if(__NR_faccessat == atoi(argv[1])) printf("%s\n", "faccessat" );
else if(__NR_faccessat2 == atoi(argv[1])) printf("%s\n", "faccessat2" );
else if(__NR_fadvise64 == atoi(argv[1])) printf("%s\n", "fadvise64" );
else if(__NR_fallocate == atoi(argv[1])) printf("%s\n", "fallocate" );
else if(__NR_fanotify_init == atoi(argv[1])) printf("%s\n", "fanotify_init" );
else if(__NR_fanotify_mark == atoi(argv[1])) printf("%s\n", "fanotify_mark" );
else if(__NR_fchdir == atoi(argv[1])) printf("%s\n", "fchdir" );
else if(__NR_fchmod == atoi(argv[1])) printf("%s\n", "fchmod" );
else if(__NR_fchmodat == atoi(argv[1])) printf("%s\n", "fchmodat" );
else if(__NR_fchown == atoi(argv[1])) printf("%s\n", "fchown" );
else if(__NR_fchownat == atoi(argv[1])) printf("%s\n", "fchownat" );
else if(__NR_fcntl == atoi(argv[1])) printf("%s\n", "fcntl" );
else if(__NR_fdatasync == atoi(argv[1])) printf("%s\n", "fdatasync" );
else if(__NR_fgetxattr == atoi(argv[1])) printf("%s\n", "fgetxattr" );
else if(__NR_finit_module == atoi(argv[1])) printf("%s\n", "finit_module" );
else if(__NR_flistxattr == atoi(argv[1])) printf("%s\n", "flistxattr" );
else if(__NR_flock == atoi(argv[1])) printf("%s\n", "flock" );
else if(__NR_fork == atoi(argv[1])) printf("%s\n", "fork" );
else if(__NR_fremovexattr == atoi(argv[1])) printf("%s\n", "fremovexattr" );
else if(__NR_fsconfig == atoi(argv[1])) printf("%s\n", "fsconfig" );
else if(__NR_fsetxattr == atoi(argv[1])) printf("%s\n", "fsetxattr" );
else if(__NR_fsmount == atoi(argv[1])) printf("%s\n", "fsmount" );
else if(__NR_fsopen == atoi(argv[1])) printf("%s\n", "fsopen" );
else if(__NR_fspick == atoi(argv[1])) printf("%s\n", "fspick" );
else if(__NR_fstat == atoi(argv[1])) printf("%s\n", "fstat" );
else if(__NR_fstatfs == atoi(argv[1])) printf("%s\n", "fstatfs" );
else if(__NR_fsync == atoi(argv[1])) printf("%s\n", "fsync" );
else if(__NR_ftruncate == atoi(argv[1])) printf("%s\n", "ftruncate" );
else if(__NR_futex == atoi(argv[1])) printf("%s\n", "futex" );
else if(__NR_futimesat == atoi(argv[1])) printf("%s\n", "futimesat" );
else if(__NR_get_kernel_syms == atoi(argv[1])) printf("%s\n", "get_kernel_syms" );
else if(__NR_get_mempolicy == atoi(argv[1])) printf("%s\n", "get_mempolicy" );
else if(__NR_get_robust_list == atoi(argv[1])) printf("%s\n", "get_robust_list" );
else if(__NR_get_thread_area == atoi(argv[1])) printf("%s\n", "get_thread_area" );
else if(__NR_getcpu == atoi(argv[1])) printf("%s\n", "getcpu" );
else if(__NR_getcwd == atoi(argv[1])) printf("%s\n", "getcwd" );
else if(__NR_getdents == atoi(argv[1])) printf("%s\n", "getdents" );
else if(__NR_getdents64 == atoi(argv[1])) printf("%s\n", "getdents64" );
else if(__NR_getegid == atoi(argv[1])) printf("%s\n", "getegid" );
else if(__NR_geteuid == atoi(argv[1])) printf("%s\n", "geteuid" );
else if(__NR_getgid == atoi(argv[1])) printf("%s\n", "getgid" );
else if(__NR_getgroups == atoi(argv[1])) printf("%s\n", "getgroups" );
else if(__NR_getitimer == atoi(argv[1])) printf("%s\n", "getitimer" );
else if(__NR_getpeername == atoi(argv[1])) printf("%s\n", "getpeername" );
else if(__NR_getpgid == atoi(argv[1])) printf("%s\n", "getpgid" );
else if(__NR_getpgrp == atoi(argv[1])) printf("%s\n", "getpgrp" );
else if(__NR_getpid == atoi(argv[1])) printf("%s\n", "getpid" );
else if(__NR_getpmsg == atoi(argv[1])) printf("%s\n", "getpmsg" );
else if(__NR_getppid == atoi(argv[1])) printf("%s\n", "getppid" );
else if(__NR_getpriority == atoi(argv[1])) printf("%s\n", "getpriority" );
else if(__NR_getrandom == atoi(argv[1])) printf("%s\n", "getrandom" );
else if(__NR_getresgid == atoi(argv[1])) printf("%s\n", "getresgid" );
else if(__NR_getresuid == atoi(argv[1])) printf("%s\n", "getresuid" );
else if(__NR_getrlimit == atoi(argv[1])) printf("%s\n", "getrlimit" );
else if(__NR_getrusage == atoi(argv[1])) printf("%s\n", "getrusage" );
else if(__NR_getsid == atoi(argv[1])) printf("%s\n", "getsid" );
else if(__NR_getsockname == atoi(argv[1])) printf("%s\n", "getsockname" );
else if(__NR_getsockopt == atoi(argv[1])) printf("%s\n", "getsockopt" );
else if(__NR_gettid == atoi(argv[1])) printf("%s\n", "gettid" );
else if(__NR_gettimeofday == atoi(argv[1])) printf("%s\n", "gettimeofday" );
else if(__NR_getuid == atoi(argv[1])) printf("%s\n", "getuid" );
else if(__NR_getxattr == atoi(argv[1])) printf("%s\n", "getxattr" );
else if(__NR_init_module == atoi(argv[1])) printf("%s\n", "init_module" );
else if(__NR_inotify_add_watch == atoi(argv[1])) printf("%s\n", "inotify_add_watch" );
else if(__NR_inotify_init == atoi(argv[1])) printf("%s\n", "inotify_init" );
else if(__NR_inotify_init1 == atoi(argv[1])) printf("%s\n", "inotify_init1" );
else if(__NR_inotify_rm_watch == atoi(argv[1])) printf("%s\n", "inotify_rm_watch" );
else if(__NR_io_cancel == atoi(argv[1])) printf("%s\n", "io_cancel" );
else if(__NR_io_destroy == atoi(argv[1])) printf("%s\n", "io_destroy" );
else if(__NR_io_getevents == atoi(argv[1])) printf("%s\n", "io_getevents" );
else if(__NR_io_pgetevents == atoi(argv[1])) printf("%s\n", "io_pgetevents" );
else if(__NR_io_setup == atoi(argv[1])) printf("%s\n", "io_setup" );
else if(__NR_io_submit == atoi(argv[1])) printf("%s\n", "io_submit" );
else if(__NR_io_uring_enter == atoi(argv[1])) printf("%s\n", "io_uring_enter" );
else if(__NR_io_uring_register == atoi(argv[1])) printf("%s\n", "io_uring_register" );
else if(__NR_io_uring_setup == atoi(argv[1])) printf("%s\n", "io_uring_setup" );
else if(__NR_ioctl == atoi(argv[1])) printf("%s\n", "ioctl" );
else if(__NR_ioperm == atoi(argv[1])) printf("%s\n", "ioperm" );
else if(__NR_iopl == atoi(argv[1])) printf("%s\n", "iopl" );
else if(__NR_ioprio_get == atoi(argv[1])) printf("%s\n", "ioprio_get" );
else if(__NR_ioprio_set == atoi(argv[1])) printf("%s\n", "ioprio_set" );
else if(__NR_kcmp == atoi(argv[1])) printf("%s\n", "kcmp" );
else if(__NR_kexec_file_load == atoi(argv[1])) printf("%s\n", "kexec_file_load" );
else if(__NR_kexec_load == atoi(argv[1])) printf("%s\n", "kexec_load" );
else if(__NR_keyctl == atoi(argv[1])) printf("%s\n", "keyctl" );
else if(__NR_kill == atoi(argv[1])) printf("%s\n", "kill" );
else if(__NR_lchown == atoi(argv[1])) printf("%s\n", "lchown" );
else if(__NR_lgetxattr == atoi(argv[1])) printf("%s\n", "lgetxattr" );
else if(__NR_link == atoi(argv[1])) printf("%s\n", "link" );
else if(__NR_linkat == atoi(argv[1])) printf("%s\n", "linkat" );
else if(__NR_listen == atoi(argv[1])) printf("%s\n", "listen" );
else if(__NR_listxattr == atoi(argv[1])) printf("%s\n", "listxattr" );
else if(__NR_llistxattr == atoi(argv[1])) printf("%s\n", "llistxattr" );
else if(__NR_lookup_dcookie == atoi(argv[1])) printf("%s\n", "lookup_dcookie" );
else if(__NR_lremovexattr == atoi(argv[1])) printf("%s\n", "lremovexattr" );
else if(__NR_lseek == atoi(argv[1])) printf("%s\n", "lseek" );
else if(__NR_lsetxattr == atoi(argv[1])) printf("%s\n", "lsetxattr" );
else if(__NR_lstat == atoi(argv[1])) printf("%s\n", "lstat" );
else if(__NR_madvise == atoi(argv[1])) printf("%s\n", "madvise" );
else if(__NR_mbind == atoi(argv[1])) printf("%s\n", "mbind" );
else if(__NR_membarrier == atoi(argv[1])) printf("%s\n", "membarrier" );
else if(__NR_memfd_create == atoi(argv[1])) printf("%s\n", "memfd_create" );
else if(__NR_migrate_pages == atoi(argv[1])) printf("%s\n", "migrate_pages" );
else if(__NR_mincore == atoi(argv[1])) printf("%s\n", "mincore" );
else if(__NR_mkdir == atoi(argv[1])) printf("%s\n", "mkdir" );
else if(__NR_mkdirat == atoi(argv[1])) printf("%s\n", "mkdirat" );
else if(__NR_mknod == atoi(argv[1])) printf("%s\n", "mknod" );
else if(__NR_mknodat == atoi(argv[1])) printf("%s\n", "mknodat" );
else if(__NR_mlock == atoi(argv[1])) printf("%s\n", "mlock" );
else if(__NR_mlock2 == atoi(argv[1])) printf("%s\n", "mlock2" );
else if(__NR_mlockall == atoi(argv[1])) printf("%s\n", "mlockall" );
else if(__NR_mmap == atoi(argv[1])) printf("%s\n", "mmap" );
else if(__NR_modify_ldt == atoi(argv[1])) printf("%s\n", "modify_ldt" );
else if(__NR_mount == atoi(argv[1])) printf("%s\n", "mount" );
else if(__NR_move_mount == atoi(argv[1])) printf("%s\n", "move_mount" );
else if(__NR_move_pages == atoi(argv[1])) printf("%s\n", "move_pages" );
else if(__NR_mprotect == atoi(argv[1])) printf("%s\n", "mprotect" );
else if(__NR_mq_getsetattr == atoi(argv[1])) printf("%s\n", "mq_getsetattr" );
else if(__NR_mq_notify == atoi(argv[1])) printf("%s\n", "mq_notify" );
else if(__NR_mq_open == atoi(argv[1])) printf("%s\n", "mq_open" );
else if(__NR_mq_timedreceive == atoi(argv[1])) printf("%s\n", "mq_timedreceive" );
else if(__NR_mq_timedsend == atoi(argv[1])) printf("%s\n", "mq_timedsend" );
else if(__NR_mq_unlink == atoi(argv[1])) printf("%s\n", "mq_unlink" );
else if(__NR_mremap == atoi(argv[1])) printf("%s\n", "mremap" );
else if(__NR_msgctl == atoi(argv[1])) printf("%s\n", "msgctl" );
else if(__NR_msgget == atoi(argv[1])) printf("%s\n", "msgget" );
else if(__NR_msgrcv == atoi(argv[1])) printf("%s\n", "msgrcv" );
else if(__NR_msgsnd == atoi(argv[1])) printf("%s\n", "msgsnd" );
else if(__NR_msync == atoi(argv[1])) printf("%s\n", "msync" );
else if(__NR_munlock == atoi(argv[1])) printf("%s\n", "munlock" );
else if(__NR_munlockall == atoi(argv[1])) printf("%s\n", "munlockall" );
else if(__NR_munmap == atoi(argv[1])) printf("%s\n", "munmap" );
else if(__NR_name_to_handle_at == atoi(argv[1])) printf("%s\n", "name_to_handle_at" );
else if(__NR_nanosleep == atoi(argv[1])) printf("%s\n", "nanosleep" );
else if(__NR_newfstatat == atoi(argv[1])) printf("%s\n", "newfstatat" );
else if(__NR_nfsservctl == atoi(argv[1])) printf("%s\n", "nfsservctl" );
else if(__NR_open == atoi(argv[1])) printf("%s\n", "open" );
else if(__NR_open_by_handle_at == atoi(argv[1])) printf("%s\n", "open_by_handle_at" );
else if(__NR_open_tree == atoi(argv[1])) printf("%s\n", "open_tree" );
else if(__NR_openat == atoi(argv[1])) printf("%s\n", "openat" );
else if(__NR_openat2 == atoi(argv[1])) printf("%s\n", "openat2" );
else if(__NR_pause == atoi(argv[1])) printf("%s\n", "pause" );
else if(__NR_perf_event_open == atoi(argv[1])) printf("%s\n", "perf_event_open" );
else if(__NR_personality == atoi(argv[1])) printf("%s\n", "personality" );
else if(__NR_pidfd_getfd == atoi(argv[1])) printf("%s\n", "pidfd_getfd" );
else if(__NR_pidfd_open == atoi(argv[1])) printf("%s\n", "pidfd_open" );
else if(__NR_pidfd_send_signal == atoi(argv[1])) printf("%s\n", "pidfd_send_signal" );
else if(__NR_pipe == atoi(argv[1])) printf("%s\n", "pipe" );
else if(__NR_pipe2 == atoi(argv[1])) printf("%s\n", "pipe2" );
else if(__NR_pivot_root == atoi(argv[1])) printf("%s\n", "pivot_root" );
else if(__NR_pkey_alloc == atoi(argv[1])) printf("%s\n", "pkey_alloc" );
else if(__NR_pkey_free == atoi(argv[1])) printf("%s\n", "pkey_free" );
else if(__NR_pkey_mprotect == atoi(argv[1])) printf("%s\n", "pkey_mprotect" );
else if(__NR_poll == atoi(argv[1])) printf("%s\n", "poll" );
else if(__NR_ppoll == atoi(argv[1])) printf("%s\n", "ppoll" );
else if(__NR_prctl == atoi(argv[1])) printf("%s\n", "prctl" );
else if(__NR_pread64 == atoi(argv[1])) printf("%s\n", "pread64" );
else if(__NR_preadv == atoi(argv[1])) printf("%s\n", "preadv" );
else if(__NR_preadv2 == atoi(argv[1])) printf("%s\n", "preadv2" );
else if(__NR_prlimit64 == atoi(argv[1])) printf("%s\n", "prlimit64" );
else if(__NR_process_madvise == atoi(argv[1])) printf("%s\n", "process_madvise" );
else if(__NR_process_vm_readv == atoi(argv[1])) printf("%s\n", "process_vm_readv" );
else if(__NR_process_vm_writev == atoi(argv[1])) printf("%s\n", "process_vm_writev" );
else if(__NR_pselect6 == atoi(argv[1])) printf("%s\n", "pselect6" );
else if(__NR_ptrace == atoi(argv[1])) printf("%s\n", "ptrace" );
else if(__NR_putpmsg == atoi(argv[1])) printf("%s\n", "putpmsg" );
else if(__NR_pwrite64 == atoi(argv[1])) printf("%s\n", "pwrite64" );
else if(__NR_pwritev == atoi(argv[1])) printf("%s\n", "pwritev" );
else if(__NR_pwritev2 == atoi(argv[1])) printf("%s\n", "pwritev2" );
else if(__NR_query_module == atoi(argv[1])) printf("%s\n", "query_module" );
else if(__NR_quotactl == atoi(argv[1])) printf("%s\n", "quotactl" );
else if(__NR_read == atoi(argv[1])) printf("%s\n", "read" );
else if(__NR_readahead == atoi(argv[1])) printf("%s\n", "readahead" );
else if(__NR_readlink == atoi(argv[1])) printf("%s\n", "readlink" );
else if(__NR_readlinkat == atoi(argv[1])) printf("%s\n", "readlinkat" );
else if(__NR_readv == atoi(argv[1])) printf("%s\n", "readv" );
else if(__NR_reboot == atoi(argv[1])) printf("%s\n", "reboot" );
else if(__NR_recvfrom == atoi(argv[1])) printf("%s\n", "recvfrom" );
else if(__NR_recvmmsg == atoi(argv[1])) printf("%s\n", "recvmmsg" );
else if(__NR_recvmsg == atoi(argv[1])) printf("%s\n", "recvmsg" );
else if(__NR_remap_file_pages == atoi(argv[1])) printf("%s\n", "remap_file_pages" );
else if(__NR_removexattr == atoi(argv[1])) printf("%s\n", "removexattr" );
else if(__NR_rename == atoi(argv[1])) printf("%s\n", "rename" );
else if(__NR_renameat == atoi(argv[1])) printf("%s\n", "renameat" );
else if(__NR_renameat2 == atoi(argv[1])) printf("%s\n", "renameat2" );
else if(__NR_request_key == atoi(argv[1])) printf("%s\n", "request_key" );
else if(__NR_restart_syscall == atoi(argv[1])) printf("%s\n", "restart_syscall" );
else if(__NR_rmdir == atoi(argv[1])) printf("%s\n", "rmdir" );
else if(__NR_rseq == atoi(argv[1])) printf("%s\n", "rseq" );
else if(__NR_rt_sigaction == atoi(argv[1])) printf("%s\n", "rt_sigaction" );
else if(__NR_rt_sigpending == atoi(argv[1])) printf("%s\n", "rt_sigpending" );
else if(__NR_rt_sigprocmask == atoi(argv[1])) printf("%s\n", "rt_sigprocmask" );
else if(__NR_rt_sigqueueinfo == atoi(argv[1])) printf("%s\n", "rt_sigqueueinfo" );
else if(__NR_rt_sigreturn == atoi(argv[1])) printf("%s\n", "rt_sigreturn" );
else if(__NR_rt_sigsuspend == atoi(argv[1])) printf("%s\n", "rt_sigsuspend" );
else if(__NR_rt_sigtimedwait == atoi(argv[1])) printf("%s\n", "rt_sigtimedwait" );
else if(__NR_rt_tgsigqueueinfo == atoi(argv[1])) printf("%s\n", "rt_tgsigqueueinfo" );
else if(__NR_sched_get_priority_max == atoi(argv[1])) printf("%s\n", "sched_get_priority_max" );
else if(__NR_sched_get_priority_min == atoi(argv[1])) printf("%s\n", "sched_get_priority_min" );
else if(__NR_sched_getaffinity == atoi(argv[1])) printf("%s\n", "sched_getaffinity" );
else if(__NR_sched_getattr == atoi(argv[1])) printf("%s\n", "sched_getattr" );
else if(__NR_sched_getparam == atoi(argv[1])) printf("%s\n", "sched_getparam" );
else if(__NR_sched_getscheduler == atoi(argv[1])) printf("%s\n", "sched_getscheduler" );
else if(__NR_sched_rr_get_interval == atoi(argv[1])) printf("%s\n", "sched_rr_get_interval" );
else if(__NR_sched_setaffinity == atoi(argv[1])) printf("%s\n", "sched_setaffinity" );
else if(__NR_sched_setattr == atoi(argv[1])) printf("%s\n", "sched_setattr" );
else if(__NR_sched_setparam == atoi(argv[1])) printf("%s\n", "sched_setparam" );
else if(__NR_sched_setscheduler == atoi(argv[1])) printf("%s\n", "sched_setscheduler" );
else if(__NR_sched_yield == atoi(argv[1])) printf("%s\n", "sched_yield" );
else if(__NR_seccomp == atoi(argv[1])) printf("%s\n", "seccomp" );
else if(__NR_security == atoi(argv[1])) printf("%s\n", "security" );
else if(__NR_select == atoi(argv[1])) printf("%s\n", "select" );
else if(__NR_semctl == atoi(argv[1])) printf("%s\n", "semctl" );
else if(__NR_semget == atoi(argv[1])) printf("%s\n", "semget" );
else if(__NR_semop == atoi(argv[1])) printf("%s\n", "semop" );
else if(__NR_semtimedop == atoi(argv[1])) printf("%s\n", "semtimedop" );
else if(__NR_sendfile == atoi(argv[1])) printf("%s\n", "sendfile" );
else if(__NR_sendmmsg == atoi(argv[1])) printf("%s\n", "sendmmsg" );
else if(__NR_sendmsg == atoi(argv[1])) printf("%s\n", "sendmsg" );
else if(__NR_sendto == atoi(argv[1])) printf("%s\n", "sendto" );
else if(__NR_set_mempolicy == atoi(argv[1])) printf("%s\n", "set_mempolicy" );
else if(__NR_set_robust_list == atoi(argv[1])) printf("%s\n", "set_robust_list" );
else if(__NR_set_thread_area == atoi(argv[1])) printf("%s\n", "set_thread_area" );
else if(__NR_set_tid_address == atoi(argv[1])) printf("%s\n", "set_tid_address" );
else if(__NR_setdomainname == atoi(argv[1])) printf("%s\n", "setdomainname" );
else if(__NR_setfsgid == atoi(argv[1])) printf("%s\n", "setfsgid" );
else if(__NR_setfsuid == atoi(argv[1])) printf("%s\n", "setfsuid" );
else if(__NR_setgid == atoi(argv[1])) printf("%s\n", "setgid" );
else if(__NR_setgroups == atoi(argv[1])) printf("%s\n", "setgroups" );
else if(__NR_sethostname == atoi(argv[1])) printf("%s\n", "sethostname" );
else if(__NR_setitimer == atoi(argv[1])) printf("%s\n", "setitimer" );
else if(__NR_setns == atoi(argv[1])) printf("%s\n", "setns" );
else if(__NR_setpgid == atoi(argv[1])) printf("%s\n", "setpgid" );
else if(__NR_setpriority == atoi(argv[1])) printf("%s\n", "setpriority" );
else if(__NR_setregid == atoi(argv[1])) printf("%s\n", "setregid" );
else if(__NR_setresgid == atoi(argv[1])) printf("%s\n", "setresgid" );
else if(__NR_setresuid == atoi(argv[1])) printf("%s\n", "setresuid" );
else if(__NR_setreuid == atoi(argv[1])) printf("%s\n", "setreuid" );
else if(__NR_setrlimit == atoi(argv[1])) printf("%s\n", "setrlimit" );
else if(__NR_setsid == atoi(argv[1])) printf("%s\n", "setsid" );
else if(__NR_setsockopt == atoi(argv[1])) printf("%s\n", "setsockopt" );
else if(__NR_settimeofday == atoi(argv[1])) printf("%s\n", "settimeofday" );
else if(__NR_setuid == atoi(argv[1])) printf("%s\n", "setuid" );
else if(__NR_setxattr == atoi(argv[1])) printf("%s\n", "setxattr" );
else if(__NR_shmat == atoi(argv[1])) printf("%s\n", "shmat" );
else if(__NR_shmctl == atoi(argv[1])) printf("%s\n", "shmctl" );
else if(__NR_shmdt == atoi(argv[1])) printf("%s\n", "shmdt" );
else if(__NR_shmget == atoi(argv[1])) printf("%s\n", "shmget" );
else if(__NR_shutdown == atoi(argv[1])) printf("%s\n", "shutdown" );
else if(__NR_sigaltstack == atoi(argv[1])) printf("%s\n", "sigaltstack" );
else if(__NR_signalfd == atoi(argv[1])) printf("%s\n", "signalfd" );
else if(__NR_signalfd4 == atoi(argv[1])) printf("%s\n", "signalfd4" );
else if(__NR_socket == atoi(argv[1])) printf("%s\n", "socket" );
else if(__NR_socketpair == atoi(argv[1])) printf("%s\n", "socketpair" );
else if(__NR_splice == atoi(argv[1])) printf("%s\n", "splice" );
else if(__NR_stat == atoi(argv[1])) printf("%s\n", "stat" );
else if(__NR_statfs == atoi(argv[1])) printf("%s\n", "statfs" );
else if(__NR_statx == atoi(argv[1])) printf("%s\n", "statx" );
else if(__NR_swapoff == atoi(argv[1])) printf("%s\n", "swapoff" );
else if(__NR_swapon == atoi(argv[1])) printf("%s\n", "swapon" );
else if(__NR_symlink == atoi(argv[1])) printf("%s\n", "symlink" );
else if(__NR_symlinkat == atoi(argv[1])) printf("%s\n", "symlinkat" );
else if(__NR_sync == atoi(argv[1])) printf("%s\n", "sync" );
else if(__NR_sync_file_range == atoi(argv[1])) printf("%s\n", "sync_file_range" );
else if(__NR_syncfs == atoi(argv[1])) printf("%s\n", "syncfs" );
else if(__NR_sysfs == atoi(argv[1])) printf("%s\n", "sysfs" );
else if(__NR_sysinfo == atoi(argv[1])) printf("%s\n", "sysinfo" );
else if(__NR_syslog == atoi(argv[1])) printf("%s\n", "syslog" );
else if(__NR_tee == atoi(argv[1])) printf("%s\n", "tee" );
else if(__NR_tgkill == atoi(argv[1])) printf("%s\n", "tgkill" );
else if(__NR_time == atoi(argv[1])) printf("%s\n", "time" );
else if(__NR_timer_create == atoi(argv[1])) printf("%s\n", "timer_create" );
else if(__NR_timer_delete == atoi(argv[1])) printf("%s\n", "timer_delete" );
else if(__NR_timer_getoverrun == atoi(argv[1])) printf("%s\n", "timer_getoverrun" );
else if(__NR_timer_gettime == atoi(argv[1])) printf("%s\n", "timer_gettime" );
else if(__NR_timer_settime == atoi(argv[1])) printf("%s\n", "timer_settime" );
else if(__NR_timerfd_create == atoi(argv[1])) printf("%s\n", "timerfd_create" );
else if(__NR_timerfd_gettime == atoi(argv[1])) printf("%s\n", "timerfd_gettime" );
else if(__NR_timerfd_settime == atoi(argv[1])) printf("%s\n", "timerfd_settime" );
else if(__NR_times == atoi(argv[1])) printf("%s\n", "times" );
else if(__NR_tkill == atoi(argv[1])) printf("%s\n", "tkill" );
else if(__NR_truncate == atoi(argv[1])) printf("%s\n", "truncate" );
else if(__NR_tuxcall == atoi(argv[1])) printf("%s\n", "tuxcall" );
else if(__NR_umask == atoi(argv[1])) printf("%s\n", "umask" );
else if(__NR_umount2 == atoi(argv[1])) printf("%s\n", "umount2" );
else if(__NR_uname == atoi(argv[1])) printf("%s\n", "uname" );
else if(__NR_unlink == atoi(argv[1])) printf("%s\n", "unlink" );
else if(__NR_unlinkat == atoi(argv[1])) printf("%s\n", "unlinkat" );
else if(__NR_unshare == atoi(argv[1])) printf("%s\n", "unshare" );
else if(__NR_uselib == atoi(argv[1])) printf("%s\n", "uselib" );
else if(__NR_userfaultfd == atoi(argv[1])) printf("%s\n", "userfaultfd" );
else if(__NR_ustat == atoi(argv[1])) printf("%s\n", "ustat" );
else if(__NR_utime == atoi(argv[1])) printf("%s\n", "utime" );
else if(__NR_utimensat == atoi(argv[1])) printf("%s\n", "utimensat" );
else if(__NR_utimes == atoi(argv[1])) printf("%s\n", "utimes" );
else if(__NR_vfork == atoi(argv[1])) printf("%s\n", "vfork" );
else if(__NR_vhangup == atoi(argv[1])) printf("%s\n", "vhangup" );
else if(__NR_vmsplice == atoi(argv[1])) printf("%s\n", "vmsplice" );
else if(__NR_vserver == atoi(argv[1])) printf("%s\n", "vserver" );
else if(__NR_wait4 == atoi(argv[1])) printf("%s\n", "wait4" );
else if(__NR_waitid == atoi(argv[1])) printf("%s\n", "waitid" );
else if(__NR_write == atoi(argv[1])) printf("%s\n", "write" );
else if(__NR_writev == atoi(argv[1])) printf("%s\n", "writev" );

}